#!/bin/bash

# Marksheet Processing - Appwrite Collection Setup Script
# This script helps you set up the academic_records collection in Appwrite

echo "🎓 Setting up Academic Records Collection in Appwrite"
echo "=================================================="
echo ""
echo "Please follow these steps in your Appwrite Console:"
echo ""
echo "1. Navigate to your Database: ${NEXT_PUBLIC_APPWRITE_DATABASE_ID}"
echo "2. Click 'Create Collection'"
echo "3. Set Collection ID: academic_records"
echo "4. Set Collection Name: Academic Records"
echo ""
echo "5. Add the following attributes:"
echo ""
echo "   STRING Attributes:"
echo "   - userId (size: 255, required: true)"
echo "   - fileId (size: 255, required: true)"
echo "   - extractedData (size: 65535, required: true)"
echo "   - institution (size: 500, required: false)"
echo "   - registerNo (size: 100, required: false)"
echo "   - studentName (size: 255, required: false)"
echo "   - dateOfBirth (size: 50, required: false)"
echo "   - department (size: 500, required: false)"
echo "   - computedCgpa (size: 10, required: false)"
echo "   - totalCreditsEarned (size: 10, required: false)"
echo "   - totalCreditsRegistered (size: 10, required: false)"
echo "   - createdAt (size: 50, required: true)"
echo "   - updatedAt (size: 50, required: true)"
echo ""
echo "6. Create an index:"
echo "   - Key: userId_index"
echo "   - Type: key"
echo "   - Attributes: userId"
echo ""
echo "7. Set Permissions:"
echo "   - Read: Role: users (All users)"
echo "   - Write: Role: users (All users)"
echo ""
echo "8. Verify in .env.local:"
echo "   NEXT_PUBLIC_APPWRITE_ACADEMIC_RECORDS_COLLECTION_ID=academic_records"
echo ""
echo "✅ Once complete, you can test at: http://localhost:3000/marksheet-upload"
echo ""
